/* Connor McClaran
   10/9/2017
   CS 3810
   HW3
*/



Copy Aircraft (AIRCRAFT_ID, AIRCRAFT_GROUP, AIRCRAFT_TYPE, AIRCRAFT_CONFIG, CLASS, SEATS)
from './Aircraft.csv' DELIMITER ',' CSV HEADER;

Copy Carrier (UNIQUE_CARRIER, AIRLINE_ID, UNIQUE_CARRIER_NAME, UNIQUE_CARRIER_ENTITY, REGION)
from './Carrier.csv' DELIMITER ',' CSV HEADER;

COPY State( State_Abr, State_Fips, State_Nm, WAC)
FROM './State.csv' DELIMITER ',' CSV HEADER;

COPY City( City_Market_ID, City_Name, State_Nm)
FROM './City.csv' DELIMITER ',' CSV HEADER;

COPY Airport( AIRPORT_ID, AIRPORT_SEQ_ID, CITY_MARKET_ID, AIRPORT)
FROM './Airport.csv' DELIMITER ',' CSV HEADER;

COPY FlightSummary(DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS, 
	PASSENGERS, FREIGHT, MAIL, DISTANCE, RAMP_TO_RAMP, AIR_TIME, 
	AIRLINE_ID, ORIGIN_AIRPORT_ID,DEST_AIRPORT_ID, YEAR, QUARTER, MONTH, 
	DISTANCE_GROUP, CLASS, AIRCRAFT_TYPE) 
FROM './flightSummaryTable.csv'DELIMITER ',' CSV HEADER;

